document.writeln("		<div class=\'navbar-default sidebar\' role=\'navigation\'>");
document.writeln("			<ul class=\'nav in\' id=\'side-menu\'>");
document.writeln("				<!--搜索-->");
document.writeln("				<li class=\'sidebar-search\'>");
document.writeln("					<div class=\'input-group custom-search-form\'>");
document.writeln("						<input type=\'text\' class=\'form-control\' placeholder=\'Search...\'>");
document.writeln("						<span class=\'input-group-btn\'>");
document.writeln("                               <button type=\'button\' class=\'btn btn-success\'><i class=\'glyphicon glyphicon-search\'></i></button>");
document.writeln("                            </span>");
document.writeln("					</div>");
document.writeln("				</li>");
document.writeln("				<!--导航-->");
document.writeln("				<li>");
document.writeln("					<a href=\'/web/home.html\'><i class=\'glyphicon glyphicon-icon glyphicon-globe\'></i> 导航</a>");
document.writeln("				</li>");
document.writeln("				<!--文章-->");
document.writeln("				<li>");
document.writeln("					<a class=\'inactive\' href=\'#\'><i class=\'glyphicon glyphicon-icon glyphicon-list-alt\'></i> 文章");
document.writeln("						<span class=\'glyphicon glyphicon-menu-left\'></span></a>");
document.writeln("					<ul class=\'nav nav-second-level collapse\' style=\'display: none\'>");
document.writeln("						<li>");
document.writeln("							<a href=\'/web/blog/addArticle.html\'>添加新文章</a>");
document.writeln("						</li>");
document.writeln("						<li>");
document.writeln("							<a href=\'#\'>文章列表</a>");
document.writeln("						</li>");
document.writeln("					</ul>");
document.writeln("				</li>");
document.writeln("				<!--分类-->");
document.writeln("				<li>");
document.writeln("					<a class=\'inactive\' href=\'#\'><i class=\'glyphicon glyphicon-icon glyphicon-inbox\'></i> 分类");
document.writeln("						<span class=\'glyphicon glyphicon-menu-left\'></span></a>");
document.writeln("					<ul class=\'nav nav-second-level collapse\' style=\'display: none\'>");
document.writeln("						<li>");
document.writeln("							<a href=\'/web/sort/addSort.html\'>添加分类</a>");
document.writeln("						</li>");
document.writeln("						<li>");
document.writeln("							<a href=\'/web/sort/listSort.html\'>分类管理</a>");
document.writeln("						</li>");
document.writeln("					</ul>");
document.writeln("				</li>");
document.writeln("				<!--评论-->");
document.writeln("				<li>");
document.writeln("					<a class=\'inactive vipp\' href=\'#\'><i class=\'glyphicon glyphicon-icon glyphicon-comment\'></i> 评论");
document.writeln("						<span class=\'glyphicon glyphicon-menu-left\'></span></a>");
document.writeln("					<ul class=\'nav nav-second-level collapse\' style=\'display: none\'>");
document.writeln("						<li>");
document.writeln("							<a href=\'#\'>建设中...</a>");
document.writeln("						</li>");
document.writeln("						<li>");
document.writeln("							<a class=\'inactive\' href=\'#\'>二级菜单可有三级<span class=\'glyphicon glyphicon-menu-left\'></a>");
document.writeln("							<ul  class=\'nav nav-three-level \' style=\'display: none\'>");
document.writeln("								<li>");
document.writeln("									<a href=\'#\'>维权办</a>");
document.writeln("								</li>");
document.writeln("								<li class=\'last\'>");
document.writeln("									<a href=\'#\'>《美术》杂志社</a>");
document.writeln("								</li>");
document.writeln("							</ul>");
document.writeln("						</li>");
document.writeln("					</ul>");
document.writeln("				</li>");
document.writeln("				<!--附件-->");
document.writeln("				<li>");
document.writeln("					<a class=\'inactive\' href=\'#\'><i class=\'glyphicon glyphicon-icon glyphicon glyphicon-saved\'></i> 附件");
document.writeln("						<span class=\'glyphicon glyphicon-menu-left\'></span></a>");
document.writeln("					<ul class=\'nav nav-second-level collapse\' style=\'display: none\'>");
document.writeln("						<li>");
document.writeln("							<a href=\'/web/attachment/addAttachment.html\'>上传附件</a>");
document.writeln("						</li>");
document.writeln("						<li>");
document.writeln("							<a href=\'/web/attachment/listAttachment.html\'>附件列表</a>");
document.writeln("						</li>");
document.writeln("					</ul>");
document.writeln("				</li>");
document.writeln("				<!--用户管理-->");
document.writeln("				<li>");
document.writeln("					<a class=\'inactive\' href=\'#\'><i class=\'glyphicon glyphicon-icon glyphicon-user\'></i> 用户管理");
document.writeln("						<span class=\'glyphicon glyphicon-menu-left\'></span></a>");
document.writeln("					<ul class=\'nav nav-second-level collapse\' style=\'display: none\'>");
document.writeln("						<li>");
document.writeln("							<a href=\'/web/user/users.html\'>用户管理</a>");
document.writeln("						</li>");
document.writeln("					</ul>");
document.writeln("				</li>");
document.writeln("			</ul>");
document.writeln("		</div>");