document.writeln("		<nav class=\'navbar navbar-default navbar-fixed-top\' role=\'navigation\'>");
document.writeln("			<div class=\'navbar-header\'>");
document.writeln("				<a class=\'navbar-brand\' href=\'/iblog/web/index.html\'>iBlog</a>");
document.writeln("			</div>");
document.writeln("			<div class=\'collapse navbar-collapse\' id=\'bs-example-navbar-collapse-1\'>");
document.writeln("				<ul class=\'nav navbar-nav\'>");
document.writeln("					<li class=\'dropdown\'>");
document.writeln("						<a href=\'#\' class=\'dropdown-toggle\' data-toggle=\'dropdown\'>快速访问 <b class=\'caret\'></b></a>");
document.writeln("						<ul class=\'dropdown-menu\'>");
document.writeln("							<li>");
document.writeln("								<a href=\'/iblog/web/cover.html\'>封面</a>");
document.writeln("							</li>");
document.writeln("							<li>");
document.writeln("								<a href=\'#\'>IT技术</a>");
document.writeln("							</li>");
document.writeln("							<li>");
document.writeln("								<a href=\'/iblog/web/about.html\'>关于</a>");
document.writeln("							</li>");
document.writeln("							<li class=\'divider\'></li>");
document.writeln("							<li role=\'presentation\' class=\'dropdown-header\'>其他</li>");
document.writeln("							<li>");
document.writeln("								<a href=\'#\'>资源下载</a>");
document.writeln("							</li>");
document.writeln("						</ul>");
document.writeln("					</li>");
document.writeln("				</ul>");
document.writeln("				<form class=\'navbar-form navbar-left\' role=\'search\'>");
document.writeln("					<div class=\'form-group\'>");
document.writeln("						<input type=\'text\' class=\'form-control\' placeholder=\'Search\'>");
document.writeln("					</div>");
document.writeln("					<button type=\'submit\' class=\'btn btn-success\'>搜索</button>");
document.writeln("				</form>");
document.writeln("");
document.writeln("				<ul class=\'nav navbar-nav navbar-right\'>");
document.writeln("					<li class=\'dropdown\' id=\'manager_top\'>");
document.writeln("						<a href=\'#\' class=\'dropdown-toggle\' data-toggle=\'dropdown\'>管理员 <b class=\'caret\'></b></a>");
document.writeln("						<ul class=\'dropdown-menu\'>");
document.writeln("							<li>");
document.writeln("								<a href=\'#\'>个人中心</a>");
document.writeln("");
document.writeln("							</li>");
document.writeln("							<li>");
document.writeln("								<a href=\'#\'>修改密码</a>");
document.writeln("							</li>");
document.writeln("							<li class=\'divider\'></li>");
document.writeln("							<li>");
document.writeln("								<a href=\'#\'>退出</a>");
document.writeln("							</li>");
document.writeln("						</ul>");
document.writeln("					</li>");
document.writeln("				</ul>");
document.writeln("			</div>");
document.writeln("		</nav>");